Fix sigma locations

diff --git a/.github/workflows/tqsp-ci.yml b/.github/workflows/tqsp-ci.yml
--- a/.github/workflows/tqsp-ci.yml
+++ b/.github/workflows/tqsp-ci.yml
@@ -39,93 +39,96 @@ jobs:
       SIGMA_HOME: ${{ github.workspace }}/sigmakee-runtime
 
     steps:
-    - uses: actions/checkout@v3
-      with:
-        path: sumo
+      - uses: actions/checkout@v3
+        with:
+          path: sumo
 
-    - name: Setup SigmaKEE
-      env:
-        ONTOLOGYPORTAL_GIT: ${{ github.workspace }}
-        SUMO_SIZE: ${{ matrix.sumo_size }}
-      run: |
-        echo "SIGMA_HOME: $SIGMA_HOME"
-        mkdir -p $SIGMA_HOME/KBs/WordNetMappings
-        wget https://raw.githubusercontent.com/ontologyportal/sigmakee/master/config.xml
-        sed -f ./sumo/tests/TQSP/$SUMO_SIZE.sed ./config.xml > $SIGMA_HOME/KBs/config.xml
-        sed -i '/<!--/,/-->/d' $SIGMA_HOME/KBs/config.xml
-        cat $SIGMA_HOME/KBs/config.xml
-        cp -R $ONTOLOGYPORTAL_GIT/sumo/* $SIGMA_HOME/KBs
-        cp /opt/WordNet-3.0/dict/* $SIGMA_HOME/KBs/WordNetMappings/
-        sed -i "s|/home/theuser/.sigmakee|$SIGMA_HOME|g" $SIGMA_HOME/KBs/config.xml
-        sed -i "s|/home/theuser/workspace/sumo|$ONTOLOGYPORTAL_GIT/sumo|g" $SIGMA_HOME/KBs/config.xml
-        sed -i "s|/home/theuser/E/bin/e_ltb_runner|/usr/local/bin/e_ltb_runner|g" $SIGMA_HOME/KBs/config.xml
-        sed -i "s|/home/theuser/workspace/vampire/vampire|/usr/local/bin/vampire|g" $SIGMA_HOME/KBs/config.xml
+      - name: Setup SigmaKEE
+        env:
+          ONTOLOGYPORTAL_GIT: ${{ github.workspace }}
+          SUMO_SIZE: ${{ matrix.sumo_size }}
+        run: |
+          echo "SIGMA_HOME: $SIGMA_HOME"
+          mkdir -p $SIGMA_HOME/KBs/WordNetMappings
+          wget https://raw.githubusercontent.com/ontologyportal/sigmakee/master/config.xml
+          sed -f ./sumo/tests/TQSP/$SUMO_SIZE.sed ./config.xml > $SIGMA_HOME/KBs/config.xml
+          sed -i '/<!--/,/-->/d' $SIGMA_HOME/KBs/config.xml
+          cat $SIGMA_HOME/KBs/config.xml
+          cp -R $ONTOLOGYPORTAL_GIT/sumo/* $SIGMA_HOME/KBs
+          cp /opt/WordNet-3.0/dict/* $SIGMA_HOME/KBs/WordNetMappings/
+          sed -i "s|/home/theuser/.sigmakee|$SIGMA_HOME|g" $SIGMA_HOME/KBs/config.xml
+          sed -i "s|/home/theuser/workspace/sumo|$ONTOLOGYPORTAL_GIT/sumo|g" $SIGMA_HOME/KBs/config.xml
+          sed -i "s|/home/theuser/E/bin/e_ltb_runner|/usr/local/bin/e_ltb_runner|g" $SIGMA_HOME/KBs/config.xml
+          sed -i "s|/home/theuser/workspace/vampire/vampire|/usr/local/bin/vampire|g" $SIGMA_HOME/KBs/config.xml
 
-    - name: Produce SUMO-${{ matrix.sumo_size }}.${{ matrix.logic }}
-      run: java -Xmx8g -classpath "/root/sigmakee/*" ${{ matrix.class }}
+      - name: Produce SUMO-${{ matrix.sumo_size }}.${{ matrix.logic }}
+        run: java -Xmx8g -classpath "/root/sigmakee/*" ${{ matrix.class }}
 
-    - name: Upload SUMO-${{ matrix.sumo_size }}.${{ matrix.logic }}
-      uses: actions/upload-artifact@v3
-      with:
-        name: SUMO-${{ matrix.sumo_size }}.${{ matrix.logic }}
-        path: ${{ env.SIGMA_HOME }}
+      - name: Upload SUMO-${{ matrix.sumo_size }}.${{ matrix.logic }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: SUMO-${{ matrix.sumo_size }}.${{ matrix.logic }}
+          path: ${{ env.SIGMA_HOME }}
 
   run_vampire:
     strategy:
       matrix:
         logic: [ tptp, tff ]
-        test_file: [SP01S, TQG01S]
+        test_file: [ SP01S, TQG01S ]
     runs-on: ubuntu-latest
-    needs: [derive_docker,build_sumo_tptp]
+    needs: [ derive_docker,build_sumo_tptp ]
     container:
       image: ${{ needs.derive_docker.outputs.image_account }}/sumo-ci:latest
     env:
       SIGMA_HOME: ${{ github.workspace }}/sigmakee-runtime
 
     steps:
-    - uses: actions/download-artifact@v3
-      with:
-        name: SUMO-top.${{ matrix.logic }}
-        path: ${{ env.SIGMA_HOME }}
+      - name: Setup SigmaKEE
+        run: |
+          echo "SIGMA_HOME: $SIGMA_HOME"
+          mkdir -p $SIGMA_HOME
 
-    - name: Run vampire against SUMO-top.${{ matrix.logic }}
-      env:
-        VAMPIRE_TIMEOUT: ${{ inputs.vampire_timeout }}
-        SUMO_FILE: SUMO-top.${{ matrix.logic }}
-        TEMPLATE_FILE: ${{ matrix.test_file }}.${{ matrix.logic }}
-        TEST_FILE: ${{ matrix.test_file }}-top.${{ matrix.logic }}
-        PROOF_TYPE: ${{ matrix.logic }}
-      working-directory: ${{ env.SIGMA_HOME }}
-      run: |
-        pwd
-        ls -l .
-        ls ./tests/TQSP/TPTP
-        sed "1i include('$SUMO_FILE')." ./tests/TQSP/TPTP/$TEMPLATE_FILE > $TEST_FILE
-        cat $TEST_FILE
-        /usr/local/bin/vampire --proof $PROOF_TYPE -t $VAMPIRE_TIMEOUT $TEST_FILE > vamp-out.txt || echo "Ignoring vampire exit code"
-        mkdir -p $SIGMA_HOME/webapps/sigma/graph
-        CATALINA_HOME=$SIGMA_HOME java -Xmx8g -classpath "/root/sigmakee/*" com.articulate.sigma.trans.TPTP3ProofProcessor -f vamp-out.txt
-        cp $SIGMA_HOME/webapps/sigma/graph/proof.* .
+      - uses: actions/download-artifact@v3
+        with:
+          name: SUMO-top.${{ matrix.logic }}
+          path: ${{ env.SIGMA_HOME }}
 
-    - name: Upload vamp-out.txt
-      if: success() || failure()
-      uses: actions/upload-artifact@v3
-      with:
-        name: logs-and-graphs
-        path: |
-          ./vamp-out.txt
-          ./proof.*
+      - name: Run vampire against SUMO-top.${{ matrix.logic }}
+        env:
+          VAMPIRE_TIMEOUT: ${{ inputs.vampire_timeout }}
+          SUMO_FILE: SUMO-top.${{ matrix.logic }}
+          TEMPLATE_FILE: ${{ matrix.test_file }}.${{ matrix.logic }}
+          TEST_FILE: ${{ matrix.test_file }}-top.${{ matrix.logic }}
+          PROOF_TYPE: ${{ matrix.logic }}
+        run: |
+          pwd
+          ls -l .
+          sed "1i include('$SIGMA_HOME/KBs/SUMO.tptp')." $SIGMA_HOME/KBs/tests/TQSP/TPTP/$TEMPLATE_FILE > $TEST_FILE
+          cat $TEST_FILE
+          /usr/local/bin/vampire --proof $PROOF_TYPE -t $VAMPIRE_TIMEOUT $TEST_FILE > vamp-out.txt || echo "Ignoring vampire exit code"
+          mkdir -p $SIGMA_HOME/webapps/sigma/graph
+          CATALINA_HOME=$SIGMA_HOME java -Xmx8g -classpath "/root/sigmakee/*" com.articulate.sigma.trans.TPTP3ProofProcessor -f vamp-out.txt
+          cp $SIGMA_HOME/webapps/sigma/graph/proof.* .
 
-    - name: Check results
-      if: success() || failure()
-      run: |
-        #allow errors
-        set +e
-        grep "Refutation found" vamp-out.txt
-        #Remap exit code. If refutation found - it's an error
-        if [ $? -eq 0 ]
-        then
-          exit 1
-        else
-          exit 0
-        fi
+      - name: Upload vamp-out.txt
+        if: success() || failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ matrix.test_file }}.${{ matrix.logic }}.logs
+          path: |
+            ./vamp-out.txt
+            ./proof.*
+
+      - name: Check results
+        if: success() || failure()
+        run: |
+          #allow errors
+          set +e
+          grep "Refutation found" vamp-out.txt
+          #Remap exit code. If refutation found - it's an error
+          if [ $? -eq 0 ]
+          then
+            exit 1
+          else
+            exit 0
+          fi
